In [9]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv('market_data.csv')
df

youtube  facebook  newspaper  sales
0      84.72     19.20      48.96  12.60
1     351.48     33.96      51.84  25.68
2     135.48     20.88      46.32  14.28
3     116.64      1.80      36.00  11.52
4     318.72     24.00       0.36  20.88
..       ...       ...        ...    ...
166    45.84      4.44      16.56   9.12
167   113.04      5.88       9.72  11.64
168   212.40     11.16       7.68  15.36
169   340.32     50.40      79.44  30.60
170   278.52     10.32      10.44  16.08

[171 rows x 4 columns]

In [11]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [12]:
X

array([[ 84.72,  19.2 ,  48.96],
       [351.48,  33.96,  51.84],
       [135.48,  20.88,  46.32],
       [116.64,   1.8 ,  36.  ],
       [318.72,  24.  ,   0.36],
       [114.84,   1.68,   8.88],
       [348.84,   4.92,  10.2 ],
       [320.28,  52.56,   6.  ],
       [ 89.64,  59.28,  54.84],
       [ 51.72,  32.04,  42.12],
       [273.6 ,  45.24,  38.4 ],
       [243.  ,  26.76,  37.92],
       [212.4 ,  40.08,  46.44],
       [352.32,  33.24,   2.16],
       [248.28,  10.08,  31.68],
       [ 30.12,  30.84,  51.96],
       [210.12,  27.  ,  37.8 ],
       [107.64,  11.88,  42.84],
       [287.88,  49.8 ,  22.2 ],
       [272.64,  18.96,  59.88],
       [ 80.28,  14.04,  44.16],
       [239.76,   3.72,  41.52],
       [120.48,  11.52,   4.32],
       [259.68,  50.04,  47.52],
       [219.12,  55.44,  70.44],
       [315.24,  34.56,  19.08],
       [238.68,  59.28,  72.  ],
       [  8.76,  33.72,  49.68],
       [163.44,  23.04,  19.92],
       [252.96,  59.52,  45.24],
       [25

In [13]:
# Normal Equation : (X.T * X) inverse * X.T * y

## insert ones column for the intercept
X = np.insert(X, 0, 1, axis=1)
X

array([[  1.  ,  84.72,  19.2 ,  48.96],
       [  1.  , 351.48,  33.96,  51.84],
       [  1.  , 135.48,  20.88,  46.32],
       [  1.  , 116.64,   1.8 ,  36.  ],
       [  1.  , 318.72,  24.  ,   0.36],
       [  1.  , 114.84,   1.68,   8.88],
       [  1.  , 348.84,   4.92,  10.2 ],
       [  1.  , 320.28,  52.56,   6.  ],
       [  1.  ,  89.64,  59.28,  54.84],
       [  1.  ,  51.72,  32.04,  42.12],
       [  1.  , 273.6 ,  45.24,  38.4 ],
       [  1.  , 243.  ,  26.76,  37.92],
       [  1.  , 212.4 ,  40.08,  46.44],
       [  1.  , 352.32,  33.24,   2.16],
       [  1.  , 248.28,  10.08,  31.68],
       [  1.  ,  30.12,  30.84,  51.96],
       [  1.  , 210.12,  27.  ,  37.8 ],
       [  1.  , 107.64,  11.88,  42.84],
       [  1.  , 287.88,  49.8 ,  22.2 ],
       [  1.  , 272.64,  18.96,  59.88],
       [  1.  ,  80.28,  14.04,  44.16],
       [  1.  , 239.76,   3.72,  41.52],
       [  1.  , 120.48,  11.52,   4.32],
       [  1.  , 259.68,  50.04,  47.52],
       [  1.  , 

In [14]:
X_Transpose = np.transpose(X) # X.T
X_Transpose

array([[  1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,
          1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  , 

In [16]:
X_Transpose_dot_X = X_Transpose @ X

In [20]:
temp1 = np.linalg.inv(X_Transpose_dot_X)

In [21]:
temp2 = X_Transpose @ y

In [22]:
thetas = temp1 @ temp2 

In [25]:
for i in range(len(thetas)):
    print(f"thetas[{i}] = {thetas[i]}\n")


thetas[0] = 3.505870994465006

thetas[1] = 0.04523544441261529

thetas[2] = 0.18839782541150818

thetas[3] = 0.004279491858703577



In [32]:
def pred_value(thetas, inputs):
    res = 0
    for i in range(len(thetas)-1):
        res = res + (thetas[i+1]*inputs[i])
    
    return (thetas[0] + res )

In [33]:

inputs =[ 84.72, 19.20, 48.96 ]
print(pred_value(thetas, inputs))


11.164980014404858
